### ISSUE TITLE
Underscore is a reserved character that was freed up with Nomnoml 1.6.0

### ISSUE THREAD

**Issue by AshlinHarris** [MichaelHatherly/NomnomlJS.jl#13]
Thanks very much for creating this package!

I tried to use an underscore in an association name with unintended results:
```julia
julia> using NomnomlJS

julia> d = Diagram("
       #background: white
       [visit] person_id - [person]
       ");

julia> write("diagram.svg", d);
```
![diagram](https://github.com/user-attachments/assets/eef16e7e-350c-49f0-8b67-0717a1b1da23)

The diagram differs from [one generated by the same input on nomnoml.com's editor](https://nomnoml.com/#view/%23background%3A%20white%0A%5Bvisit%5D%20person_id%20-%20%5Bperson%5D):

![_background_ white__visit_ person_id - _person_](https://github.com/user-attachments/assets/ee39135b-1d75-4d3b-97b3-a7b353256869)

The root cause is that underscores were previously used to designate [weightless edges](https://github.com/MichaelHatherly/NomnomlJS.jl/blob/85277fed584b373b6b11a04fcf4851ee62be7703/src/NomnomlJS.jl#L31-L32), which have been [removed with Nomnoml 1.6.0](https://github.com/skanaar/nomnoml/issues/160#issuecomment-1556214365).

This appears to be [the only breaking change since 1.5 ](https://github.com/skanaar/nomnoml/issues/202#issuecomment-1549732787), at least.

Could you please publish another major release of NomnomlJS.jl with an updated backend? If needed, I could prepare a PR for this, but it might take some time. There is currently an [unmerged pull request to update the dependency from 1.3.1 to 1.6.3](https://github.com/MichaelHatherly/NomnomlJS.jl/pull/8).

**Comment by AshlinHarris** [comment]
As a workaround, I can replace replace underscores with a fullwidth low line `＿`:

![diagram](https://github.com/user-attachments/assets/9e3106c8-900f-46f2-ad1f-ce418a2e4042)

A space+combining lowline ` ̲ `can be a closer visual match, but only when viewed in a Pluto notebook.

**Comment by MichaelHatherly** [comment]
I'll see if I can get an updated build sorted.
